feat: pull languages cmd
storyblok/storyblok-cli pull request #129
Opened 2024-10-31 10:30 UTC by alvarosabu

Hi, this is the new implementation of the `pull-components` command for the renovated version of the CLI.

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR

1. Clone the repo and pull the branch
2. Add several languages to a Storyblok Space or use the default test one `295017` or `295018`
3. Run `pnpm install`
4. Run `pnpm run dev pull-languages --space <SPACE_ID>`

### Testing checklist

- [ ] pull languages with a space with languages configured.
  - [ ] should create a `languages.295017.json` file on the root containing an object 
  ```json
  {
    "languages": [
      {
        "code": "de",
        "name": "German"
      },
      {
        "code": "ja",
        "name": "Japanese"
      },
      {
        "code": "pl",
        "name": "Polish"
      }
    ]
  }
  ```
  - [ ] file should contain `"default_lang_name": "en",` if configured on the space
  - [ ] should prompt an error if flag space is missing
  - [ ] should prompt an API error if the space ID is incorrect
  - [ ] should prompt an unauthorized error if the user is not logged in before operating this command

2024-11-04 10:52 UTC, edodusi requested changes
Adding some code comments, proceeding to manual testing!

2024-11-04 10:52 UTC, edodusi commented on src/commands/pull-languages/actions.ts
> +    return {
I think this return statement would be better placed after the `catch` block, as it's not part of the code that can throw and also for better readability - you can even put it inside a `finally` block

2024-11-04 10:52 UTC, edodusi commented on src/commands/pull-languages/actions.ts
> +  }
this code could also be refactored to follow the try...catch flow, like this for example

```
import { writeFile, mkdir, access, constants } from 'fs/promises'
import { resolve, join } from 'path'
import { SpaceInternationalizationOptions } from 'actual-module-name' // Replace with the actual module name
import { handleFileSystemError } from 'actual-module-name' // Replace with the actual module name

export const saveLanguagesToFile = async (space: string, internationalizationOptions: SpaceInternationalizationOptions, path?: string) => {
  const data = JSON.stringify(internationalizationOptions, null, 2)
  const filename = `languages.${space}.json`
  const resolvedPath = path ? resolve(process.cwd(), path) : process.cwd()
  const filePath = join(resolvedPath, filename)

  try {
    await access(resolvedPath, constants.F_OK)
  } catch {
    try {
      await mkdir(resolvedPath, { recursive: true })
    } catch (mkdirError) {
      handleFileSystemError('mkdir', mkdirError as Error)
    }
  }

  try {
    await writeFile(filePath, data, { mode: 0o600 })
  } catch (error) {
    handleFileSystemError('write', error as Error)
  }
}
 ```

2024-11-04 10:52 UTC, edodusi commented on src/commands/pull-languages/index.ts
> +      if (!internationalization || internationalization.languages.length === 0) {
can `languages` be undefined? in this case I will be more resilient with

`if (!internationalization || !internationalization.languages || internationalization.languages.length === 0) {`

2024-11-04 11:05 UTC, edodusi commented
@alvarosabu I manually tested and checked everything 🚀 

One thing, the steps you provided mention that I should have `"default_lang_name": "en",` in the json file, while I have `"default_lang_name": "english",`, is this correct?

2024-11-04 11:09 UTC, alvarosabu commented
> @alvarosabu I manually tested and checked everything 🚀
> 
> One thing, the steps you provided mention that I should have `"default_lang_name": "en",` in the json file, while I have `"default_lang_name": "english",`, is this correct?

Awesome, thanks for testing it.

Thats weird. My JSON looks like this:

```
{
  "default_lang_name": "en",
  "languages": [
    {
      "code": "de",
      "name": "German"
    },
    {
      "code": "ja",
      "name": "Japanese"
    },
    {
      "code": "pl",
      "name": "Polish"
    }
  ]
}
```

2024-11-05 08:19 UTC, alvarosabu commented on src/commands/pull-languages/actions.ts
> +    return {
Hi, @edodusi the return should remain inside of the try-catch.

If you add it after, the code can't find the name `response` 

<img width="954" alt="Screenshot 2024-11-05 at 09 14 04" src="https://github.com/user-attachments/assets/36b83568-431f-499b-a3d6-65e61539cf22">


finally, it is also not a safe option in this case, check https://eslint.org/docs/latest/rules/no-unsafe-finally

<img width="639" alt="Screenshot 2024-11-05 at 09 13 29" src="https://github.com/user-attachments/assets/742e0140-5b46-4cac-a2b4-61de0c4e8c14">

2024-11-05 08:29 UTC, edodusi commented on src/commands/pull-languages/actions.ts
> +    return {
right, that makes sense

2024-11-05 08:48 UTC, edodusi approved these changes
👍

2024-11-05 10:39 UTC, merged