Add Group UUID Filtering for Components
storyblok/storyblok-cli pull request #37
Opened 2023-04-11 08:50 UTC by CaprinaeWT

## Pull request type

Jira Link: [INT-](url)

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR

1. Run the command to test the new group UUID filtering feature:
`./cli.js sync --type components --source <source-space-id> --target <target-space-id> --c-groups <group-uuid-1>,<group-uuid-2>,...` 

Please note that the --c-groups flag enables the filter based on the provided group UUIDs. To test the feature, replace <source-value> and <target-value> with the actual values of the source and target.

2. Verify that only the components belonging to the specified group UUIDs are synchronized between the source and target. Any components that do not belong to the specified group UUIDs should not be synchronized.

3. Try different combinations of group UUIDs to verify that the filter works as expected.

Thank you for testing the new group UUID filtering feature. Your feedback is highly appreciated.

## What is the new behaviour?

This pull request introduces a new feature that allows for filtering components based on their group UUID. With this new feature, users can specify one or more group UUIDs and synchronise only the components that belong to those groups.

The new feature is especially useful in scenarios where users need to manage a large number of components across different groups and need a way to easily synchronise components based on group membership.

The implementation includes a new filtering logic, which supports filtering based on the provided group UUIDs. The feature is also fully documented, with clear instructions on how to use the new filtering options.

Thank you for your attention and consideration.

## Other information

2023-04-19 14:53 UTC, ademarCardoso commented on src/cli.js
> +      const _cGroups = cGroups ? cGroups.split(',') : null
I think it's better to change to `componentsGroups`, it is better for readability in the code.

2023-04-19 14:54 UTC, ademarCardoso commented on src/tasks/sync-commands/components.js
> +    this.cGroups = options.cGroups
Same thing here, `this.componentsGroups`

2023-04-19 14:54 UTC, ademarCardoso commented on src/tasks/sync.js
> +    this.cGroups = options._cGroups
Same here

2023-04-19 16:26 UTC, ademarCardoso commented
Hi @CaprinaeWT you added `;` in a lot of places in your last commit `c93789a`, please, revert this changes 😄 , we don't use `;` at the end of the lines. Thanks

2023-04-19 17:08 UTC, CaprinaeWT commented
Hey @ademarCardoso, My bad. 😅

2023-04-19 22:24 UTC, ademarCardoso approved these changes
It's a great contribution to the code base, thanks for the help my friend.
I will pass it on to our QA to do the final tests and in a few days I believe we can launch a release with this new feature 🚀

2023-04-28 12:26 UTC, thiagosaife requested changes
I left some comments about naming changes.

2023-04-28 12:26 UTC, thiagosaife commented on src/cli.js
> +  .option('--c-groups <UUIDs>', 'Synchronize components based on their group UUIDs separated by commas')
@CaprinaeWT Please change `--c-groups` to `--components-groups`. We do prefer the names as descriptive as possible. Thank you.

2023-04-28 12:26 UTC, thiagosaife commented on src/cli.js
> +        cGroups
@CaprinaeWT same here. From `cGroups` to `componentsGroups`.

2023-04-28 13:14 UTC, thiagosaife approved these changes

2023-04-28 18:05 UTC, merged